trigger:
  branches:
    include:
      - dev

pool:
  name: 'Default'

variables:
  solution: 'main/Project-file/*.sln' 
  buildConfiguration: 'Release'
  artifactName: 'drop'

stages:

# ------------------- Build Stage -------------------
- stage: Build
  displayName: 'Build .NET Framework WebApp'
  jobs:
    - job: BuildJob
      displayName: 'Build Job'
      steps:
        - task: NuGetToolInstaller@1

        - task: NuGetCommand@2
          inputs:
            restoreSolution: '$(solution)'

        # Auto-detect MSBuild using vswhere.exe
        - powershell: |
            $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
            if (-Not (Test-Path $vswhere)) { 
                throw "vswhere.exe not found. Install Visual Studio or Build Tools first." 
            }

            $msbuildPath = & $vswhere -latest -products * -requires Microsoft.Component.MSBuild -find "**\MSBuild\**\Bin\MSBuild.exe"
            if (-Not $msbuildPath) { 
                throw "MSBuild not found via vswhere. Please install Build Tools." 
            }

            Write-Host "MSBuild located at: $msbuildPath"
            & $msbuildPath "$(solution)" `
              /p:Configuration=$(buildConfiguration) `
              /p:DeployOnBuild=true `
              /p:WebPublishMethod=FileSystem `
              /p:OutDir="$(Build.ArtifactStagingDirectory)\WebApp\"
          displayName: 'Build with auto-detected MSBuild'

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)\WebApp'
            ArtifactName: '$(artifactName)'
            publishLocation: 'Container'

# ------------------- Deploy Stage -------------------
- stage: Deploy
  displayName: 'Deploy to Azure VM IIS'
  dependsOn: Build
  jobs:
    - deployment: DeployToVM
      displayName: 'Deploy to IIS'
      environment: 'Lexitas-IIS-Dev'
      strategy:
        runOnce:
          deploy:
            steps:
              # Download build artifacts
              - task: DownloadPipelineArtifact@2
                inputs:
                  artifactName: '$(artifactName)'
                  targetPath: '$(System.DefaultWorkingDirectory)\WebApp'

              # Backup existing IIS website
              - powershell: |
                  $timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
                  $sourcePath = "C:\inetpub\wwwroot\MyWebApp"
                  $backupPath = "C:\inetpub\wwwroot\Backups\MyWebApp_$timestamp"
                  if (Test-Path $sourcePath) {
                      New-Item -ItemType Directory -Force -Path $backupPath
                      Copy-Item -Path "$sourcePath\*" -Destination $backupPath -Recurse
                      Write-Host "Backup completed: $backupPath"
                  } else {
                      Write-Host "No existing app found to backup."
                  }
                displayName: 'Backup Existing Website'

              # Deploy new build
              - powershell: |
                  $source = "$(System.DefaultWorkingDirectory)\WebApp\"
                  $destination = "C:\inetpub\wwwroot\MyWebApp"
                  if (-Not (Test-Path $destination)) {
                      New-Item -ItemType Directory -Force -Path $destination
                  }
                  Remove-Item "$destination\*" -Recurse -Force -ErrorAction SilentlyContinue
                  Copy-Item -Path "$source\*" -Destination $destination -Recurse -Force
                displayName: 'Deploy New Build to IIS'

              # Restart only your App Pool
              - powershell: |
                  Restart-WebAppPool -Name "MyWebAppPool"
                displayName: 'Restart IIS App Pool'
